[package]
name = "wallpaper-downloader"
version = "0.1.0"
authors = ["F5XS <f5xs.0000a@gmail.com>"]

[dependencies]
reqwest = "*"
cursive = "*"
parking_lot = "*"
tokio-threadpool = "*"
serde = "1.0.78"
serde_derive = "1.0.78"

[dependencies.sekibanki]
path = "../LICHTFANTASIE/sekibanki/"
